controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

articles:
    path: /images/articles
    controller: App\Controller\GetFileUrlController::getFileUrl

users:
    path: /images/users
    controller: App\Controller\GetFileUrlController::getFileUrl
